# Generated by Django 5.1.15 on 2026-09-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='catalogo.herramienta')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
