# Generated by Django 5.1.15 on 2026-09-23 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def completar_unidades(apps, schema_editor):
    """Transferencias que ya existan: cantidad_unidades con el tamaño de
    caja actual de la herramienta (la 0004 vuelve el campo NOT NULL en una
    transacción aparte, como en movimientos 0003/0004)."""
    Transferencia = apps.get_model("transferencias", "Transferencia")
    for t in Transferencia.objects.select_related("herramienta").filter(cantidad_unidades__isnull=True):
        factor = t.herramienta.unidades_por_caja if t.tipo_unidad == "CAJA" else 1
        t.cantidad_unidades = t.cantidad * factor
        t.save(update_fields=["cantidad_unidades"])


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_tipos_transferencia'),
        ('transferencias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='cantidad_unidades',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='motivo_rechazo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='movimiento_entrada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='movimientos.movimiento'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='movimiento_salida',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='movimientos.movimiento'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(completar_unidades, migrations.RunPython.noop),
    ]
