# Generated by Django 5.1.15 on 2026-09-22 18:34

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.CharField(max_length=64)),
                ('accion', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('usuario_username', models.CharField(blank=True, max_length=150)),
                ('datos_anteriores', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de modificación',
                'verbose_name_plural': 'Historial de modificaciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tabla_afectada', 'registro_id'], name='auditoria_h_tabla_a_bfd351_idx')],
            },
        ),
    ]
