# Generated by Django 5.1.15 on 2026-09-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('tipo_unidad', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.herramienta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
