# Generated by Django 5.1.15 on 2026-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_ajustes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('TRANSFERENCIA_SALIDA', 'Transferencia salida'), ('TRANSFERENCIA_ENTRADA', 'Transferencia entrada')], max_length=25),
        ),
    ]
