# Generated by Django 5.1.15 on 2026-09-22 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='costo_almacenamiento_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='H: costo de almacenar una unidad durante un año.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='costo_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='S: costo fijo de hacer un pedido al proveedor.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='demanda_anual',
            field=models.PositiveIntegerField(blank=True, help_text='D: unidades vendidas al año (estimado).', null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='tiempo_entrega_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Días que tarda el proveedor en entregar un pedido.', null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
